package com.github.tth05.teth.cli.commands;

import com.github.tth05.teth.bytecode.program.TethProgram;
import picocli.CommandLine;

@CommandLine.Command(
        name = "bc",
        description = "Dumps the generated bytecode for a given file",
        synopsisHeading = "@|bold,underline Usage|@:%n  ",
        descriptionHeading = "@|bold,underline Description|@:%n  ",
        parameterListHeading = "@|bold,underline Parameters|@:%n",
        optionListHeading = "@|bold,underline Options|@:%n"
)
public class BytecodeCommand extends AbstractCompilerCommand {

    @Override
    protected void run(TethProgram program) {
        var instructions = program.getInstructions();
        for (int i = 0; i < instructions.length; i++) {
            System.out.println(i + ": " + instructions[i].getDebugString());
        }
    }
}
